// gen-preload.js — 构建期生成 preload-handlers.js
//
// 读取项目契约的 bridgeApi，生成 handlers 文件。
// preload.js 手写，引用生成的 handlers。
//
// 用法：
//   node src/update-kit/tools/gen-preload.js
//
// 生成物：
//   src/application/preload-handlers.js — 只包含 handlers 对象
//
// 红线：纯 node，零 electron 依赖。
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '../../..');
const contractFile = path.join(projectRoot, 'update-kit.contract.json');

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    throw new Error(`读取契约失败: ${file}（${e.message}）`);
  }
}

const contract = readJson(contractFile);
const bridgeApi = contract.bridgeApi || [];
const handlersPath = path.join(projectRoot, 'src/application/preload-handlers.js');

// 按 type 生成 handlers 内容
function generateHandlers(bridgeApi) {
  const lines = [
    '// GENERATED by update-kit/tools/gen-preload.js — do not edit',
    '// 修改 bridgeApi 后必须重新生成：npm run gen-preload',
    "'use strict';",
    "const { ipcRenderer } = require('electron');",
    '',
    'const handlers = {',
  ];

  for (const api of bridgeApi) {
    const { name, type, channel } = api;
    if (type === 'invoke') {
      lines.push(`  ${name}: (...args) => ipcRenderer.invoke('${channel}', ...args),`);
    } else if (type === 'send') {
      lines.push(`  ${name}: (...args) => ipcRenderer.send('${channel}', ...args),`);
    } else if (type === 'on') {
      lines.push(`  ${name}: (cb) => ipcRenderer.on('${channel}', (_e, v) => cb(v)),`);
    } else {
      throw new Error(`未知的 bridgeApi type: ${type}`);
    }
  }

  lines.push(
    '};',
    '',
    'module.exports = handlers;',
    ''
  );

  return lines.join('\n');
}

const content = generateHandlers(bridgeApi);
fs.mkdirSync(path.dirname(handlersPath), { recursive: true });
fs.writeFileSync(handlersPath, content);

console.log(`✓ 已生成 preload-handlers: ${path.relative(projectRoot, handlersPath)}`);
console.log(`  bridgeApi: ${bridgeApi.length} 个`);
