// gen-preload.js — 构建期生成 preload.js
//
// 读取项目契约的 bridgeApi，生成 paths.preload 指向的文件。
// 生成物提交进 git，属于 shell 单元。
//
// 用法：
//   node src/update-kit/tools/gen-preload.js
//
// 红线：纯 node，零 electron 依赖。
'use strict';
const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '../../..');
const contractFile = path.join(projectRoot, 'update-kit.contract.json');

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    throw new Error(`读取契约失败: ${file}（${e.message}）`);
  }
}

const contract = readJson(contractFile);
const bridgeApi = contract.bridgeApi || [];
const preloadPath = path.resolve(projectRoot, contract.paths.preload);

// 按 type 生成 preload 内容
function generatePreload(bridgeApi) {
  const lines = [
    '// GENERATED by update-kit/tools/gen-preload.js — do not edit',
    '// 修改 bridgeApi 后必须重新生成：npm run gen-preload',
    "'use strict';",
    "const { contextBridge, ipcRenderer } = require('electron');",
    '',
    'const handlers = {',
  ];

  for (const api of bridgeApi) {
    const { name, type, channel } = api;
    if (type === 'invoke') {
      lines.push(`  ${name}: (...args) => ipcRenderer.invoke('${channel}', ...args),`);
    } else if (type === 'send') {
      lines.push(`  ${name}: (...args) => ipcRenderer.send('${channel}', ...args),`);
    } else if (type === 'on') {
      lines.push(`  ${name}: (cb) => ipcRenderer.on('${channel}', (_e, v) => cb(v)),`);
    } else {
      throw new Error(`未知的 bridgeApi type: ${type}`);
    }
  }

  lines.push(
    '};',
    '',
    'const declared = ['
  );

  for (const api of bridgeApi) {
    lines.push(`  '${api.name}',`);
  }

  lines.push(
    '];',
    '',
    'const unimplemented = declared.filter((k) => !Object.prototype.hasOwnProperty.call(handlers, k));',
    'const undeclared = Object.keys(handlers).filter((k) => !declared.includes(k));',
    '',
    'if (unimplemented.length || undeclared.length) {',
    '  const msg = \'[preload] window.api 契约不一致：\' +',
    '    (unimplemented.length ? `注册表声明但未实现: ${unimplemented.join(\', \')}. ` : \'\') +',
    '    (undeclared.length ? `已实现但未登记: ${undeclared.join(\', \')}.\` : \'\');',
    '  throw new Error(msg);',
    '}',
    '',
    'const api = {};',
    'for (const k of declared) api[k] = handlers[k];',
    'contextBridge.exposeInMainWorld(\'api\', api);',
    ''
  );

  return lines.join('\n');
}

const content = generatePreload(bridgeApi);
fs.mkdirSync(path.dirname(preloadPath), { recursive: true });
fs.writeFileSync(preloadPath, content);

console.log(`✓ 已生成 preload: ${path.relative(projectRoot, preloadPath)}`);
console.log(`  bridgeApi: ${bridgeApi.length} 个`);
